import { defineModel, defineProvider } from "../../scripts/lib/index";
import type { ScrapeResult } from "../../scripts/lib/types";
import type { Model, ModelModality, Pricing } from "../../types/index";

const provider = defineProvider({
  id: "aimlapi",
  name: "AI/ML API",
  url: "https://aimlapi.com",
  api_docs: "https://aimlapi.com/ai-ml-api-pricing",
  apis: {
    openai: "https://api.aimlapi.com/v1",
  },
});

// ---------------------------------------------------------------------------
// Hardcoded model data (from first-party sources accessed 2026-05-17)
//
// Sources:
// - Pricing page: https://aimlapi.com/ai-ml-api-pricing (Webflow SSR)
// - Model list: https://api.aimlapi.com/v1/models (public API, 441 models)
//
// AI/ML API is an inference platform hosting models from other providers
// (OpenAI, Anthropic, Google, DeepSeek, Alibaba Cloud, xAI, MiniMax,
// Zhipu AI, Moonshot AI, ByteDance, Baidu, NVIDIA, Xiaomi, Perplexity,
// NousResearch) with its own per-token pricing (per 1M tokens, USD).
//
// Pricing shown is AI/ML API's per-1M-token rate (USD).
// Model IDs are derived from the website pricing page model names.
// ---------------------------------------------------------------------------

interface ModelInfo {
  name: string;
  context: number;
  output: number;
  inputModalities: ModelModality[];
  outputModalities: ModelModality[];
}

const MODELS: Record<string, ModelInfo> = {
  "xai--grok-4-3": {
    name: "xAI / Grok 4.3",
    context: 1000000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "nvidia--nemotron-3-nano-omni": {
    name: "NVIDIA / Nemotron 3 Nano Omni",
    context: 256000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "nvidia--nemotron-3-super-120b-a12b": {
    name: "NVIDIA / Nemotron 3 Super 120B-A12B",
    context: 1000000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "nvidia--nemotron-3-nano-30b-a3b": {
    name: "NVIDIA / Nemotron 3 Nano 30B A3B",
    context: 262000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "alibaba-cloud--qwen3-5-flash": {
    name: "Alibaba Cloud / Qwen3.5-Flash",
    context: 1000000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "openai--gpt-5-5-pro": {
    name: "OpenAI / GPT-5.5 Pro",
    context: 1000000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "deepseek--deepseek-v4-pro": {
    name: "DeepSeek / DeepSeek V4 Pro",
    context: 1000000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "alibaba-cloud--qwen3-5-omni-flash": {
    name: "Alibaba Cloud / Qwen3.5 Omni Flash",
    context: 256000,
    output: 8192,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "alibaba-cloud--qwen3-5-omni-plus": {
    name: "Alibaba Cloud / Qwen3.5 Omni Plus",
    context: 256000,
    output: 8192,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "bytedance--dola-seed-2-0-code": {
    name: "ByteDance / Dola-Seed-2.0 Code",
    context: 256000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "bytedance--dola-seed-2-0-mini": {
    name: "ByteDance / Dola-Seed 2.0 Mini",
    context: 256000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "bytedance--dola-seed-2-0-lite": {
    name: "ByteDance / Dola-Seed 2.0 Lite",
    context: 256000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "bytedance--dola-seed-2-0-pro": {
    name: "ByteDance / Dola-Seed 2.0 Pro",
    context: 256000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "alibaba-cloud--qwen3-6-flash": {
    name: "Alibaba Cloud / Qwen3.6-Flash",
    context: 1000000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "alibaba-cloud--qwen3-6-max-preview": {
    name: "Alibaba Cloud / Qwen3.6 Max Preview",
    context: 262000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "alibaba-cloud--qwen3-6-plus": {
    name: "Alibaba Cloud / Qwen3.6-Plus",
    context: 1000000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "alibaba-cloud--qwen3-6-35b-a3b": {
    name: "Alibaba Cloud / Qwen3.6-35B-A3B",
    context: 262000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "xiaomi--mimo-v2-5": {
    name: "Xiaomi / MiMo-V2.5",
    context: 1000000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "xiaomi--mimo-v2-5-pro": {
    name: "Xiaomi / MiMo-V2.5 Pro",
    context: 1000000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "alibaba-cloud--qwen-3-6-27b": {
    name: "Alibaba Cloud / Qwen 3.6 27B",
    context: 262000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "moonshot-ai--kimi-k2-6": {
    name: "Moonshot AI / Kimi K2.6",
    context: 262000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "anthropic--claude-opus-4-7": {
    name: "Anthropic / Claude Opus 4.7",
    context: 1000000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "minimax--minimax-m2-1-highspeed": {
    name: "MiniMax / MiniMax M2.1 Highspeed",
    context: 200000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "minimax--minimax-m2-7-highspeed": {
    name: "MiniMax / MiniMax M2.7 Highspeed",
    context: 200000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "minimax--minimax-m2-her": {
    name: "MiniMax / MiniMax M2-her",
    context: 65000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "xai--grok-4-20": {
    name: "xAI / Grok 4.20",
    context: 2000000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "zhipu-ai--glm-5-1": {
    name: "Zhipu AI / GLM-5.1",
    context: 200000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "deepseek--deepseek-4-flash": {
    name: "DeepSeek / DeepSeek 4 Flash",
    context: 1000000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "google--gemini-3-1-flash-lite-preview": {
    name: "Google / Gemini 3.1 Flash Lite Preview",
    context: 1000000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "google--gemma-4-31b": {
    name: "Google / Gemma 4 31B",
    context: 262000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "minimax--minimax-m2-7": {
    name: "MiniMax / MiniMax M2.7",
    context: 200000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "openai--gpt-5-4-pro": {
    name: "OpenAI / GPT‑5.4 Pro",
    context: 1000000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "openai--gpt-5-4": {
    name: "OpenAI / GPT-5.4",
    context: 1000000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "minimax--minimax-m2-5": {
    name: "MiniMax / MiniMax-M2.5",
    context: 1000000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "alibaba-cloud--qwen3-5-plus": {
    name: "Alibaba Cloud / Qwen3.5 Plus",
    context: 1000000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "google--gemini-3-1-pro": {
    name: "Google / Gemini 3.1 Pro",
    context: 1000000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "anthropic--claude-sonnet-4-6": {
    name: "Anthropic / Claude Sonnet 4.6",
    context: 1000000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "zhipu-ai--glm-5": {
    name: "Zhipu AI / GLM-5",
    context: 200000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "moonshot-ai--kimi-k2-5": {
    name: "Moonshot AI / Kimi K2.5",
    context: 262000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "anthropic--claude-opus-4-6": {
    name: "Anthropic / Claude Opus 4.6",
    context: 200000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "baidu--ernie-4-5-0-3b": {
    name: "Baidu / ERNIE 4.5 0.3B",
    context: 131000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "baidu--ernie-x1": {
    name: "Baidu / ERNIE X1",
    context: 200000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "baidu--ernie-5-0": {
    name: "Baidu / ERNIE 5.0",
    context: 128000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "xiaomi--mimo-v2-flash": {
    name: "Xiaomi / MiMo-V2-Flash",
    context: 256000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "baidu--ernie-4-5-vl": {
    name: "Baidu / ERNIE 4.5 VL",
    context: 32000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "baidu--ernie-4-5": {
    name: "Baidu / ERNIE 4.5",
    context: 131000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "bytedance--bytedance-seed-1-8": {
    name: "ByteDance / ByteDance Seed 1.8",
    context: 256000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "minimax--minimax-m2-1": {
    name: "MiniMax / MiniMax-M2.1",
    context: 200000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "zhipu-ai--glm-4-7": {
    name: "Zhipu AI / GLM-4.7",
    context: 200000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "google--gemini-3-flash": {
    name: "Google / Gemini 3 Flash",
    context: 1000000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "openai--gpt-5-2-chat-latest": {
    name: "OpenAI / GPT-5.2 Chat Latest",
    context: 400000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "openai--gpt-5-2-pro": {
    name: "OpenAI / GPT-5.2 Pro",
    context: 400000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "openai--gpt-5-2": {
    name: "OpenAI / GPT-5.2",
    context: 400000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "deepseek--deepseek-v3-2-speciale": {
    name: "DeepSeek / DeepSeek-V3.2 Speciale",
    context: 128000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "anthropic--claude-opus-4-5": {
    name: "Anthropic / Claude Opus 4.5",
    context: 200000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "xai--grok-4-1-fast": {
    name: "xAI / Grok 4.1 Fast",
    context: 2000000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "openai--gpt-5-1-chat-latest": {
    name: "OpenAI / GPT-5.1 Chat Latest",
    context: 128000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "openai--gpt-5-1": {
    name: "OpenAI / GPT-5.1",
    context: 128000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "nousresearch--hermes-4-405b": {
    name: "NousResearch / Hermes 4 405B",
    context: 131000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "nvidia--nemotron-nano-12b-v2-vl": {
    name: "NVIDIA / Nemotron Nano 12B V2 VL",
    context: 131000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "nvidia--nemotron-nano-9b-v2": {
    name: "NVIDIA / Nemotron Nano 9B V2",
    context: 131000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "moonshot-ai--kimi-k2-0905-preview": {
    name: "Moonshot AI / Kimi K2 0905 Preview",
    context: 262000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "alibaba-cloud--qwen3-vl-32b-instruct": {
    name: "Alibaba Cloud / Qwen3 VL 32B Instruct",
    context: 126000,
    output: 8192,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "alibaba-cloud--qwen3-vl-32b-thinking": {
    name: "Alibaba Cloud / Qwen3 VL 32B Thinking",
    context: 126000,
    output: 8192,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "moonshot-ai--kimi-k2-turbo-preview": {
    name: "Moonshot AI / Kimi K2 Turbo Preview",
    context: 262000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "minimax--minimax-m2": {
    name: "MiniMax / MiniMax M2",
    context: 200000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "alibaba-cloud--qwen3-vl-flash": {
    name: "Alibaba Cloud / Qwen3 VL Flash",
    context: 262000,
    output: 8192,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "alibaba-cloud--qwen3-vl-plus": {
    name: "Alibaba Cloud / Qwen3 VL Plus",
    context: 262000,
    output: 8192,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "anthropic--claude-4-5-haiku-by-anthropic": {
    name: "Anthropic / Claude 4.5 Haiku by Anthropic",
    context: 200000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "deepseek--deepseek-v3-1-terminus": {
    name: "DeepSeek / DeepSeek-V3.1 Terminus",
    context: 128000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "openai--gpt-5-pro": {
    name: "OpenAI / GPT-5 Pro",
    context: 400000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "deepseek--deepseek-v3-2-exp-non-thinking": {
    name: "DeepSeek / DeepSeek-V3.2-Exp Non-Thinking",
    context: 128000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "deepseek--deepseek-v3-2-exp-thinking": {
    name: "DeepSeek / DeepSeek‑V3.2‑Exp Thinking",
    context: 128000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "zhipu-ai--glm-4-6": {
    name: "Zhipu AI / GLM-4.6",
    context: 200000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "alibaba-cloud--qwen3-max-instruct": {
    name: "Alibaba Cloud / Qwen3-Max Instruct",
    context: 262000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "anthropic--claude-4-5-sonnet-thinking": {
    name: "Anthropic / Claude 4.5 Sonnet Thinking",
    context: 200000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "xai--grok-4-fast-non-reasoning": {
    name: "xAI / Grok 4 Fast Non-Reasoning",
    context: 2000000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "xai--grok-4-fast-reasoning": {
    name: "xAI / Grok 4 Fast Reasoning",
    context: 2000000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "alibaba-cloud--qwen3-next-80b-a3b-instruct": {
    name: "Alibaba Cloud / Qwen3-Next-80B-A3B Instruct",
    context: 256000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "alibaba-cloud--qwen3-next-80b-a3b-thinking": {
    name: "Alibaba Cloud / Qwen3-Next-80B-A3B Thinking",
    context: 256000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "alibaba-cloud--qwen3-max-preview": {
    name: "Alibaba Cloud / Qwen3-Max Preview",
    context: 256000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "deepseek--deepseek-v3-1": {
    name: "DeepSeek / DeepSeek-V3.1",
    context: 128000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "deepseek--deepseek-v3-1-release": {
    name: "DeepSeek / DeepSeek-V3.1 Release",
    context: 128000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "openai--gpt-5-chat": {
    name: "OpenAI / GPT-5 Chat",
    context: 400000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "openai--gpt-5-nano": {
    name: "OpenAI / GPT-5 Nano",
    context: 400000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "openai--gpt-5-mini": {
    name: "OpenAI / GPT-5 Mini",
    context: 400000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "openai--gpt-5": {
    name: "OpenAI / GPT-5",
    context: 400000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "anthropic--claude-opus-4-1": {
    name: "Anthropic / Claude Opus 4.1",
    context: 200000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "openai--gpt-oss-20b": {
    name: "OpenAI / GPT OSS 20B",
    context: 128000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "openai--gpt-oss-120b": {
    name: "OpenAI / GPT OSS 120B",
    context: 128000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "zhipu-ai--glm-4-5-air": {
    name: "Zhipu AI / GLM-4.5 Air",
    context: 128000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "zhipu-ai--glm-4-5": {
    name: "Zhipu AI / GLM-4.5",
    context: 128000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "alibaba-cloud--qwen3-32b": {
    name: "Alibaba Cloud / Qwen3 32B",
    context: 131000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "perplexity--sonar-pro": {
    name: "Perplexity / Sonar Pro",
    context: 200000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "perplexity--sonar": {
    name: "Perplexity / Sonar",
    context: 128000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "moonshot-ai--kimi-k2": {
    name: "Moonshot AI / Kimi K2",
    context: 131000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "xai--grok-4": {
    name: "xAI / Grok 4",
    context: 256000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "openai--openai-o3-pro": {
    name: "OpenAI / OpenAI o3-Pro",
    context: 200000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "minimax--minimax-m1": {
    name: "MiniMax / MiniMax M1",
    context: 1000000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "openai--gpt-5-3-codex": {
    name: "OpenAI / GPT-5.3 Codex",
    context: 1000000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "openai--gpt-5-2-codex": {
    name: "OpenAI / GPT-5.2 Codex",
    context: 400000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "openai--gpt-5-1-codex-mini": {
    name: "OpenAI / GPT-5.1 Codex Mini",
    context: 400000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "openai--gpt-5-1-codex": {
    name: "OpenAI / GPT-5.1 Codex",
    context: 400000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "xai--grok-code-fast-1": {
    name: "xAI / Grok Code Fast 1",
    context: 256000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "alibaba-cloud--qwen3-coder": {
    name: "Alibaba Cloud / Qwen3 Coder",
    context: 262000,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
};

const HARDCODED_PRICING: Record<string, Pricing> = {
  "xai--grok-4-3": { currency: "USD", input: 3.25, output: 6.5 },
  "nvidia--nemotron-3-nano-omni": { unit: "free" },
  "nvidia--nemotron-3-super-120b-a12b": {
    currency: "USD",
    input: 0.117,
    output: 0.585,
  },
  "nvidia--nemotron-3-nano-30b-a3b": {
    currency: "USD",
    input: 0.065,
    output: 0.26,
  },
  "alibaba-cloud--qwen3-5-flash": { currency: "USD", input: 0.13, output: 0.52 },
  "openai--gpt-5-5-pro": { currency: "USD", input: 39.0, output: 234.0 },
  "deepseek--deepseek-v4-pro": { currency: "USD", input: 2.262, output: 4.524 },
  "alibaba-cloud--qwen3-5-omni-flash": {
    currency: "USD",
    input: 0.52,
    output: 2.86,
  },
  "alibaba-cloud--qwen3-5-omni-plus": {
    currency: "USD",
    input: 1.82,
    output: 10.79,
  },
  "bytedance--dola-seed-2-0-code": { currency: "USD", input: 0.65, output: 3.9 },
  "bytedance--dola-seed-2-0-mini": { currency: "USD", input: 0.13, output: 0.52 },
  "bytedance--dola-seed-2-0-lite": { currency: "USD", input: 0.325, output: 2.6 },
  "bytedance--dola-seed-2-0-pro": { currency: "USD", input: 0.65, output: 3.9 },
  "alibaba-cloud--qwen3-6-flash": { currency: "USD", input: 0.325, output: 1.95 },
  "alibaba-cloud--qwen3-6-max-preview": {
    currency: "USD",
    input: 1.69,
    output: 10.14,
  },
  "alibaba-cloud--qwen3-6-plus": { currency: "USD", input: 0.65, output: 0.39 },
  "alibaba-cloud--qwen3-6-35b-a3b": { currency: "USD", input: 0.375, output: 2.25 },
  "xiaomi--mimo-v2-5": { currency: "USD", input: 0.4, output: 2.0 },
  "xiaomi--mimo-v2-5-pro": { currency: "USD", input: 1.0, output: 3.0 },
  "alibaba-cloud--qwen-3-6-27b": { currency: "USD", input: 0.78, output: 4.68 },
  "moonshot-ai--kimi-k2-6": { currency: "USD", input: 0.208, output: 5.2 },
  "anthropic--claude-opus-4-7": { currency: "USD", input: 6.5, output: 32.5 },
  "minimax--minimax-m2-1-highspeed": { currency: "USD", input: 0.78, output: 3.12 },
  "minimax--minimax-m2-7-highspeed": { currency: "USD", input: 0.78, output: 3.12 },
  "minimax--minimax-m2-her": { currency: "USD", input: 0.39, output: 1.56 },
  "xai--grok-4-20": { currency: "USD", input: 2.6, output: 7.8 },
  "zhipu-ai--glm-5-1": { currency: "USD", input: 1.82, output: 5.72 },
  "deepseek--deepseek-4-flash": { currency: "USD", input: 0.182, output: 0.364 },
  "google--gemini-3-1-flash-lite-preview": {
    currency: "USD",
    input: 0.33,
    output: 1.95,
  },
  "google--gemma-4-31b": { currency: "USD", input: 0.5486, output: 0.5486 },
  "minimax--minimax-m2-7": { currency: "USD", input: 0.39, output: 1.56 },
  "openai--gpt-5-4-pro": { currency: "USD", input: 39.0, output: 234.0 },
  "openai--gpt-5-4": { currency: "USD", input: 3.25, output: 19.5 },
  "minimax--minimax-m2-5": { currency: "USD", input: 0.39, output: 1.56 },
  "alibaba-cloud--qwen3-5-plus": { currency: "USD", input: 1.56, output: 9.36 },
  "google--gemini-3-1-pro": { currency: "USD", input: 2.6, output: 15.6 },
  "anthropic--claude-sonnet-4-6": { currency: "USD", input: 3.9, output: 19.5 },
  "zhipu-ai--glm-5": { currency: "USD", input: 1.3, output: 4.16 },
  "moonshot-ai--kimi-k2-5": { currency: "USD", input: 0.78, output: 3.9 },
  "anthropic--claude-opus-4-6": { currency: "USD", input: 6.5, output: 32.5 },
  "baidu--ernie-4-5-0-3b": { unit: "free" },
  "baidu--ernie-x1": { currency: "USD", input: 0.2145, output: 0.858 },
  "baidu--ernie-5-0": { currency: "USD", input: 1.2298, output: 2.0449 },
  "xiaomi--mimo-v2-flash": { currency: "USD", input: 0.1107, output: 0.3323 },
  "baidu--ernie-4-5-vl": { currency: "USD", input: 0.6435, output: 1.859 },
  "baidu--ernie-4-5": { currency: "USD", input: 0.0936, output: 0.3718 },
  "bytedance--bytedance-seed-1-8": { currency: "USD", input: 0.65, output: 5.2 },
  "minimax--minimax-m2-1": { currency: "USD", input: 0.39, output: 1.56 },
  "zhipu-ai--glm-4-7": { currency: "USD", input: 0.78, output: 2.86 },
  "google--gemini-3-flash": { currency: "USD", input: 0.65, output: 3.9 },
  "openai--gpt-5-2-chat-latest": { currency: "USD", input: 2.275, output: 18.2 },
  "openai--gpt-5-2-pro": { currency: "USD", input: 27.3, output: 218.4 },
  "openai--gpt-5-2": { currency: "USD", input: 2.275, output: 18.2 },
  "deepseek--deepseek-v3-2-speciale": {
    currency: "USD",
    input: 0.36855,
    output: 0.56186,
  },
  "anthropic--claude-opus-4-5": { currency: "USD", input: 6.5, output: 32.5 },
  "xai--grok-4-1-fast": { currency: "USD", input: 0.26, output: 0.65 },
  "openai--gpt-5-1-chat-latest": { currency: "USD", input: 1.625, output: 13.0 },
  "openai--gpt-5-1": { currency: "USD", input: 1.625, output: 13.0 },
  "nousresearch--hermes-4-405b": {
    currency: "USD",
    input: 0.41145,
    output: 1.6458,
  },
  "nvidia--nemotron-nano-12b-v2-vl": {
    currency: "USD",
    input: 0.2743,
    output: 0.8229,
  },
  "nvidia--nemotron-nano-9b-v2": {
    currency: "USD",
    input: 0.05486,
    output: 0.21944,
  },
  "moonshot-ai--kimi-k2-0905-preview": {
    currency: "USD",
    input: 0.195,
    output: 3.25,
  },
  "alibaba-cloud--qwen3-vl-32b-instruct": {
    currency: "USD",
    input: 0.91,
    output: 3.64,
  },
  "alibaba-cloud--qwen3-vl-32b-thinking": {
    currency: "USD",
    input: 0.91,
    output: 10.92,
  },
  "moonshot-ai--kimi-k2-turbo-preview": {
    currency: "USD",
    input: 0.78,
    output: 13.0,
  },
  "minimax--minimax-m2": { currency: "USD", input: 0.39, output: 1.56 },
  "alibaba-cloud--qwen3-vl-flash": { currency: "USD", input: 0.065, output: 0.52 },
  "alibaba-cloud--qwen3-vl-plus": { currency: "USD", input: 0.26, output: 2.08 },
  "anthropic--claude-4-5-haiku-by-anthropic": {
    currency: "USD",
    input: 1.3,
    output: 6.5,
  },
  "deepseek--deepseek-v3-1-terminus": {
    currency: "USD",
    input: 0.364,
    output: 0.546,
  },
  "openai--gpt-5-pro": { currency: "USD", input: 19.5, output: 156.0 },
  "deepseek--deepseek-v3-2-exp-non-thinking": {
    currency: "USD",
    input: 0.364,
    output: 0.546,
  },
  "deepseek--deepseek-v3-2-exp-thinking": {
    currency: "USD",
    input: 0.364,
    output: 0.546,
  },
  "zhipu-ai--glm-4-6": { currency: "USD", input: 0.78, output: 2.86 },
  "alibaba-cloud--qwen3-max-instruct": {
    currency: "USD",
    input: 1.56,
    output: 7.8,
  },
  "anthropic--claude-4-5-sonnet-thinking": {
    currency: "USD",
    input: 3.9,
    output: 19.5,
  },
  "xai--grok-4-fast-non-reasoning": { currency: "USD", input: 0.52, output: 1.3 },
  "xai--grok-4-fast-reasoning": { currency: "USD", input: 0.52, output: 1.3 },
  "alibaba-cloud--qwen3-next-80b-a3b-instruct": {
    currency: "USD",
    input: 0.195,
    output: 1.56,
  },
  "alibaba-cloud--qwen3-next-80b-a3b-thinking": {
    currency: "USD",
    input: 0.195,
    output: 1.56,
  },
  "alibaba-cloud--qwen3-max-preview": { currency: "USD", input: 1.56, output: 7.8 },
  "deepseek--deepseek-v3-1": { currency: "USD", input: 0.294, output: 0.441 },
  "deepseek--deepseek-v3-1-release": {
    currency: "USD",
    input: 0.294,
    output: 0.441,
  },
  "openai--gpt-5-chat": { currency: "USD", input: 1.625, output: 13.0 },
  "openai--gpt-5-nano": { currency: "USD", input: 0.065, output: 0.52 },
  "openai--gpt-5-mini": { currency: "USD", input: 0.325, output: 2.6 },
  "openai--gpt-5": { currency: "USD", input: 1.625, output: 13.0 },
  "anthropic--claude-opus-4-1": { currency: "USD", input: 19.5, output: 97.5 },
  "openai--gpt-oss-20b": { currency: "USD", input: 0.041145, output: 0.189735 },
  "openai--gpt-oss-120b": { currency: "USD", input: 0.05486, output: 0.5486 },
  "zhipu-ai--glm-4-5-air": { currency: "USD", input: 0.26, output: 1.43 },
  "zhipu-ai--glm-4-5": { currency: "USD", input: 0.78, output: 2.86 },
  "alibaba-cloud--qwen3-32b": { currency: "USD", input: 0.208, output: 0.832 },
  "perplexity--sonar-pro": { currency: "USD", input: 3.9, output: 19.5 },
  "perplexity--sonar": { currency: "USD", input: 1.3, output: 1.3 },
  "moonshot-ai--kimi-k2": { currency: "USD", input: 0.195, output: 3.25 },
  "xai--grok-4": { currency: "USD", input: 7.8, output: 39.0 },
  "openai--openai-o3-pro": { currency: "USD", input: 26.0, output: 104.0 },
  "minimax--minimax-m1": { currency: "USD", input: 1.69, output: 2.86 },
  "openai--gpt-5-3-codex": { currency: "USD", input: 2.275, output: 18.2 },
  "openai--gpt-5-2-codex": { currency: "USD", input: 1.8375, output: 14.7 },
  "openai--gpt-5-1-codex-mini": { currency: "USD", input: 0.325, output: 2.6 },
  "openai--gpt-5-1-codex": { currency: "USD", input: 1.625, output: 13.0 },
  "xai--grok-code-fast-1": { currency: "USD", input: 0.26, output: 1.95 },
  "alibaba-cloud--qwen3-coder": { currency: "USD", input: 1.95, output: 9.75 },
};

// ---------------------------------------------------------------------------
// Family derivation
// ---------------------------------------------------------------------------

function deriveFamily(id: string): string {
  const prefix = id.split("--")[0] as string;
  const map: Record<string, string> = {
    anthropic: "claude",
    openai: "gpt",
    google: "gemini",
    deepseek: "deepseek",
    "alibaba-cloud": "qwen",
    xai: "grok",
    minimax: "minimax",
    "zhipu-ai": "glm",
    "moonshot-ai": "kimi",
    xiaomi: "mimo",
    bytedance: "seed",
    baidu: "ernie",
    nvidia: "nemotron",
    "mistral-ai": "mistral",
    meta: "llama",
    nousresearch: "hermes",
    perplexity: "sonar",
  };
  const mapped = map[prefix as keyof typeof map];
  return mapped !== undefined ? mapped : prefix;
}

// ---------------------------------------------------------------------------
// Scrape function
// ---------------------------------------------------------------------------

export async function scrape(): Promise<ScrapeResult> {
  const today = new Date().toISOString().split("T")[0] as string;
  const models: Model[] = [];

  for (const [id, info] of Object.entries(MODELS)) {
    const pricing = HARDCODED_PRICING[id];
    if (!pricing) {
      console.warn(`  AI/ML API: skipping ${id} — no pricing`);
      continue;
    }

    const modelDef: Parameters<typeof defineModel>[0] = {
      id,
      name: info.name,
      family: deriveFamily(id),
      limit: { context: info.context, output: info.output },
      modalities: { input: info.inputModalities, output: info.outputModalities },
      pricing,
      release_date: today,
      last_updated: today,
    };

    models.push(defineModel(modelDef));
  }

  console.log(`  AI/ML API: ${models.length} models`);

  return { provider, models };
}
