import { defineModel, defineProvider } from "../../scripts/lib/index";
import type { ScrapeResult } from "../../scripts/lib/types";
import type { Model, ModelModality, Pricing } from "../../types/index";

const provider = defineProvider({
  id: "302ai",
  name: "302.AI",
  url: "https://302.ai",
  api_docs: "https://302.ai/docs",
  apis: {
    openai: "https://dash-api.302.ai/v1",
  },
});

// ---------------------------------------------------------------------------
// Hardcoded model data (from first-party sources accessed 2026-05-16)
//
// Sources:
// - Pricing: https://302.ai/product/list?cate=api&tag=语言大模型
//   (CSR-rendered page, browser-scraped first-party data)
//   Data extracted by navigating each brand sub-page and parsing model cards
//   with per-token pricing. All prices are USD per million tokens.
// - Context lengths: Cross-referenced with official provider documentation
// - Model IDs: 302.AI model card identifiers
//
// 302.AI is a Chinese AI platform and inference router hosting models from
// 20+ providers with per-token USD pricing.
//
// Pricing shown is USD per million tokens.
// DeepSeek "-aliyun"/"-baidu"/"-huoshan" suffixes = different hosting regions.
// "-thinking" suffix = extended reasoning / chain-of-thought mode.
// Gemini "-search"/"-deepsearch" = search-augmented variants.
// ---------------------------------------------------------------------------

interface ModelInfo {
  name: string;
  context: number;
  output: number;
  inputModalities: ModelModality[];
  outputModalities: ModelModality[];
  toolCall?: boolean;
  openWeights?: boolean;
  reasoning?: boolean;
}

const MODELS: Record<string, ModelInfo> = {
  "Baichuan-M2": {
    name: "Baichuan-M2 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "Baichuan-M2-Plus": {
    name: "Baichuan-M2-Plus on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "Baichuan-M3": {
    name: "Baichuan-M3 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "Baichuan3-Turbo": {
    name: "Baichuan3-Turbo on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "Baichuan3-Turbo-128k": {
    name: "Baichuan3-Turbo-128k on 302.AI",
    context: 128000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  Baichuan4: {
    name: "Baichuan4 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "DeepSeek-R1-0528": {
    name: "DeepSeek-R1-0528 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    openWeights: true,
    reasoning: true,
  },
  "Doubao-1.5-lite-32k": {
    name: "Doubao-1.5-lite-32k on 302.AI",
    context: 32000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "Doubao-1.5-pro-256k": {
    name: "Doubao-1.5-pro-256k on 302.AI",
    context: 256000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "Doubao-1.5-pro-32k": {
    name: "Doubao-1.5-pro-32k on 302.AI",
    context: 32000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "Doubao-Seed-2.0-Code": {
    name: "Doubao-Seed-2.0-Code on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "Doubao-Seed-2.0-lite": {
    name: "Doubao-Seed-2.0-lite on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "Doubao-Seed-2.0-mini": {
    name: "Doubao-Seed-2.0-mini on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "Doubao-Seed-2.0-pro": {
    name: "Doubao-Seed-2.0-pro on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "KAT-Coder-Pro-V1": {
    name: "KAT-Coder-Pro-V1 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "LongCat-Flash-Chat": {
    name: "LongCat-Flash-Chat on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "M2-Her": {
    name: "M2-Her on 302.AI",
    context: 1048576,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "MAI-DS-R1": {
    name: "MAI-DS-R1 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    openWeights: true,
    reasoning: true,
  },
  "MiniMax-M1": {
    name: "MiniMax-M1 on 302.AI",
    context: 1048576,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "MiniMax-M2": {
    name: "MiniMax-M2 on 302.AI",
    context: 1048576,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "MiniMax-M2.1": {
    name: "MiniMax-M2.1 on 302.AI",
    context: 1048576,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "MiniMax-M2.5": {
    name: "MiniMax-M2.5 on 302.AI",
    context: 1048576,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "MiniMax-M2.5-highspeed": {
    name: "MiniMax-M2.5-highspeed on 302.AI",
    context: 1048576,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "MiniMax-M2.7": {
    name: "MiniMax-M2.7 on 302.AI",
    context: 1048576,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "MiniMax-M2.7-highspeed": {
    name: "MiniMax-M2.7-highspeed on 302.AI",
    context: 1048576,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "MiniMax-Text-01": {
    name: "MiniMax-Text-01 on 302.AI",
    context: 1048576,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    openWeights: true,
  },
  "Phi-4-mini-reasoning": {
    name: "Phi-4-mini-reasoning on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    openWeights: true,
    reasoning: true,
  },
  "Phi-4-reasoning": {
    name: "Phi-4-reasoning on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    openWeights: true,
    reasoning: true,
  },
  "SenseChat-5": {
    name: "SenseChat-5 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "SenseChat-Turbo": {
    name: "SenseChat-Turbo on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "SenseNova-V6-Pro": {
    name: "SenseNova-V6-Pro on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "SenseNova-V6-Reasoner": {
    name: "SenseNova-V6-Reasoner on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    reasoning: true,
  },
  "SenseNova-V6-Turbo": {
    name: "SenseNova-V6-Turbo on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "abab6.5s-chat": {
    name: "abab6.5s-chat on 302.AI",
    context: 1048576,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "abab7-chat-preview": {
    name: "abab7-chat-preview on 302.AI",
    context: 1048576,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "chat-latest": {
    name: "chat-latest on 302.AI",
    context: 128000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "claude-3-5-haiku": {
    name: "claude-3-5-haiku on 302.AI",
    context: 200000,
    output: 8192,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "claude-haiku-4-5-20251001": {
    name: "claude-haiku-4-5-20251001 on 302.AI",
    context: 200000,
    output: 8192,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "claude-opus-4-1-20250805": {
    name: "claude-opus-4-1-20250805 on 302.AI",
    context: 200000,
    output: 32000,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "claude-opus-4-1-20250805-thinking": {
    name: "claude-opus-4-1-20250805-thinking on 302.AI",
    context: 200000,
    output: 32000,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    reasoning: true,
  },
  "claude-opus-4-20250514": {
    name: "claude-opus-4-20250514 on 302.AI",
    context: 200000,
    output: 32000,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "claude-opus-4-20250514-thinking": {
    name: "claude-opus-4-20250514-thinking on 302.AI",
    context: 200000,
    output: 32000,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    reasoning: true,
  },
  "claude-opus-4-5-20251101": {
    name: "claude-opus-4-5-20251101 on 302.AI",
    context: 200000,
    output: 32000,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "claude-opus-4-6": {
    name: "claude-opus-4-6 on 302.AI",
    context: 200000,
    output: 32000,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "claude-opus-4-6-thinking": {
    name: "claude-opus-4-6-thinking on 302.AI",
    context: 200000,
    output: 32000,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    reasoning: true,
  },
  "claude-opus-4-7": {
    name: "claude-opus-4-7 on 302.AI",
    context: 200000,
    output: 32000,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "claude-sonnet-4-20250514": {
    name: "claude-sonnet-4-20250514 on 302.AI",
    context: 200000,
    output: 32000,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "claude-sonnet-4-20250514-thinking": {
    name: "claude-sonnet-4-20250514-thinking on 302.AI",
    context: 200000,
    output: 32000,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    reasoning: true,
  },
  "claude-sonnet-4-5-20250929": {
    name: "claude-sonnet-4-5-20250929 on 302.AI",
    context: 200000,
    output: 32000,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "claude-sonnet-4-5-20250929-thinking": {
    name: "claude-sonnet-4-5-20250929-thinking on 302.AI",
    context: 200000,
    output: 32000,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    reasoning: true,
  },
  "claude-sonnet-4-6": {
    name: "claude-sonnet-4-6 on 302.AI",
    context: 200000,
    output: 32000,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "claude-sonnet-4-6-thinking": {
    name: "claude-sonnet-4-6-thinking on 302.AI",
    context: 200000,
    output: 32000,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    reasoning: true,
  },
  "deepseek-r1": {
    name: "deepseek-r1 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    openWeights: true,
    reasoning: true,
  },
  "deepseek-r1-aliyun": {
    name: "deepseek-r1-aliyun on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    reasoning: true,
  },
  "deepseek-r1-baidu": {
    name: "deepseek-r1-baidu on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    reasoning: true,
  },
  "deepseek-r1-huoshan": {
    name: "deepseek-r1-huoshan on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    reasoning: true,
  },
  "deepseek-r1-huoshan-0528": {
    name: "deepseek-r1-huoshan-0528 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    reasoning: true,
  },
  "deepseek-v3-0324": {
    name: "deepseek-v3-0324 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    openWeights: true,
  },
  "deepseek-v3-aliyun": {
    name: "deepseek-v3-aliyun on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "deepseek-v3-baidu": {
    name: "deepseek-v3-baidu on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "deepseek-v3-huoshan": {
    name: "deepseek-v3-huoshan on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "deepseek-v3.1": {
    name: "deepseek-v3.1 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "deepseek-v3.1-huoshan": {
    name: "deepseek-v3.1-huoshan on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "deepseek-v3.1-thinking": {
    name: "deepseek-v3.1-thinking on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    reasoning: true,
  },
  "deepseek-v3.2": {
    name: "deepseek-v3.2 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "deepseek-v3.2-exp": {
    name: "deepseek-v3.2-exp on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    openWeights: true,
  },
  "deepseek-v3.2-exp-thinking": {
    name: "deepseek-v3.2-exp-thinking on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    openWeights: true,
    reasoning: true,
  },
  "deepseek-v3.2-thinking": {
    name: "deepseek-v3.2-thinking on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    reasoning: true,
  },
  "deepseek-v4-flash": {
    name: "deepseek-v4-flash on 302.AI",
    context: 1048576,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "deepseek-v4-pro": {
    name: "deepseek-v4-pro on 302.AI",
    context: 1048576,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "deepseek-vl2": {
    name: "deepseek-vl2 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    openWeights: true,
  },
  "devstral-2512": {
    name: "devstral-2512 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "devstral-medium-2507": {
    name: "devstral-medium-2507 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "devstral-small-2505": {
    name: "devstral-small-2505 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    openWeights: true,
  },
  "devstral-small-2507": {
    name: "devstral-small-2507 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    openWeights: true,
  },
  "doubao-1-5-thinking-pro-250415": {
    name: "doubao-1-5-thinking-pro-250415 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    reasoning: true,
  },
  "doubao-1-5-thinking-pro-vision-250415": {
    name: "doubao-1-5-thinking-pro-vision-250415 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    reasoning: true,
  },
  "doubao-1-5-thinking-vision-pro-250428": {
    name: "doubao-1-5-thinking-vision-pro-250428 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    reasoning: true,
  },
  "doubao-1.5-ui-tars-250328": {
    name: "doubao-1.5-ui-tars-250328 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "doubao-1.5-vision-lite-250315": {
    name: "doubao-1.5-vision-lite-250315 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "doubao-1.5-vision-pro-250328": {
    name: "doubao-1.5-vision-pro-250328 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "doubao-seed-1-6-250615": {
    name: "doubao-seed-1-6-250615 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "doubao-seed-1-6-flash-250615": {
    name: "doubao-seed-1-6-flash-250615 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    openWeights: true,
  },
  "doubao-seed-1-6-thinking-250615": {
    name: "doubao-seed-1-6-thinking-250615 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    reasoning: true,
  },
  "doubao-seed-1-6-vision-250815": {
    name: "doubao-seed-1-6-vision-250815 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "doubao-seed-1-8-251215": {
    name: "doubao-seed-1-8-251215 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "doubao-seed-code-preview-251028": {
    name: "doubao-seed-code-preview-251028 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "doubao-seed-code-preview-latest": {
    name: "doubao-seed-code-preview-latest on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "ernie-4.0-8k": {
    name: "ernie-4.0-8k on 302.AI",
    context: 8192,
    output: 4096,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "ernie-4.0-turbo-128k": {
    name: "ernie-4.0-turbo-128k on 302.AI",
    context: 128000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "ernie-4.0-turbo-8k": {
    name: "ernie-4.0-turbo-8k on 302.AI",
    context: 8192,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "ernie-4.5-8k-preview": {
    name: "ernie-4.5-8k-preview on 302.AI",
    context: 8192,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "ernie-4.5-turbo-128k": {
    name: "ernie-4.5-turbo-128k on 302.AI",
    context: 128000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "ernie-4.5-turbo-vl-32k": {
    name: "ernie-4.5-turbo-vl-32k on 302.AI",
    context: 32000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "ernie-5.0-thinking-latest": {
    name: "ernie-5.0-thinking-latest on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    reasoning: true,
  },
  "ernie-5.0-thinking-preview": {
    name: "ernie-5.0-thinking-preview on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    reasoning: true,
  },
  "ernie-x1-turbo-32k": {
    name: "ernie-x1-turbo-32k on 302.AI",
    context: 32000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    reasoning: true,
  },
  "ernie-x1.1-preview": {
    name: "ernie-x1.1-preview on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    reasoning: true,
  },
  "gemini-2.0-flash": {
    name: "gemini-2.0-flash on 302.AI",
    context: 1048576,
    output: 8192,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gemini-2.0-flash-exp-search": {
    name: "gemini-2.0-flash-exp-search on 302.AI",
    context: 1048576,
    output: 8192,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gemini-2.0-flash-lite": {
    name: "gemini-2.0-flash-lite on 302.AI",
    context: 1048576,
    output: 8192,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gemini-2.0-flash-search": {
    name: "gemini-2.0-flash-search on 302.AI",
    context: 1048576,
    output: 8192,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gemini-2.5-flash": {
    name: "gemini-2.5-flash on 302.AI",
    context: 1048576,
    output: 65536,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gemini-2.5-flash-deepsearch": {
    name: "gemini-2.5-flash-deepsearch on 302.AI",
    context: 1048576,
    output: 65536,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gemini-2.5-flash-lite": {
    name: "gemini-2.5-flash-lite on 302.AI",
    context: 1048576,
    output: 65536,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gemini-2.5-flash-lite-preview-09-2025": {
    name: "gemini-2.5-flash-lite-preview-09-2025 on 302.AI",
    context: 1048576,
    output: 65536,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gemini-2.5-flash-nothink": {
    name: "gemini-2.5-flash-nothink on 302.AI",
    context: 1048576,
    output: 65536,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gemini-2.5-flash-preview-09-2025": {
    name: "gemini-2.5-flash-preview-09-2025 on 302.AI",
    context: 1048576,
    output: 65536,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gemini-2.5-flash-search": {
    name: "gemini-2.5-flash-search on 302.AI",
    context: 1048576,
    output: 65536,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gemini-2.5-pro": {
    name: "gemini-2.5-pro on 302.AI",
    context: 1048576,
    output: 65536,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gemini-2.5-pro-deepsearch": {
    name: "gemini-2.5-pro-deepsearch on 302.AI",
    context: 1048576,
    output: 65536,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gemini-2.5-pro-search": {
    name: "gemini-2.5-pro-search on 302.AI",
    context: 1048576,
    output: 65536,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gemini-3-flash-preview": {
    name: "gemini-3-flash-preview on 302.AI",
    context: 1000000,
    output: 65536,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gemini-3-pro-preview": {
    name: "gemini-3-pro-preview on 302.AI",
    context: 2000000,
    output: 65536,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gemini-3.1-flash-lite-preview": {
    name: "gemini-3.1-flash-lite-preview on 302.AI",
    context: 2000000,
    output: 65536,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gemini-3.1-pro-preview": {
    name: "gemini-3.1-pro-preview on 302.AI",
    context: 2000000,
    output: 65536,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gemma-2-27b": {
    name: "gemma-2-27b on 302.AI",
    context: 8192,
    output: 8192,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    openWeights: true,
  },
  "glm-4-air-250414": {
    name: "glm-4-air-250414 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    openWeights: true,
  },
  "glm-4-flash-250414": {
    name: "glm-4-flash-250414 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    openWeights: true,
  },
  "glm-4.1v-thinking-flashx": {
    name: "glm-4.1v-thinking-flashx on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    openWeights: true,
    reasoning: true,
  },
  "glm-4.5": {
    name: "glm-4.5 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "glm-4.5-air": {
    name: "glm-4.5-air on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "glm-4.5-airx": {
    name: "glm-4.5-airx on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "glm-4.5-x": {
    name: "glm-4.5-x on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "glm-4.5v": {
    name: "glm-4.5v on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "glm-4.6": {
    name: "glm-4.6 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "glm-4.6v": {
    name: "glm-4.6v on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "glm-4.7": {
    name: "glm-4.7 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "glm-4.7-flashx": {
    name: "glm-4.7-flashx on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "glm-5": {
    name: "glm-5 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "glm-5-turbo": {
    name: "glm-5-turbo on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "glm-5.1": {
    name: "glm-5.1 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "glm-5v-turbo": {
    name: "glm-5v-turbo on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "glm-for-coding": {
    name: "glm-for-coding on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gpt-5": {
    name: "gpt-5 on 302.AI",
    context: 400000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gpt-5-2025-08-07": {
    name: "gpt-5-2025-08-07 on 302.AI",
    context: 400000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gpt-5-chat-latest": {
    name: "gpt-5-chat-latest on 302.AI",
    context: 128000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gpt-5-codex": {
    name: "gpt-5-codex on 302.AI",
    context: 400000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gpt-5-mini": {
    name: "gpt-5-mini on 302.AI",
    context: 400000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gpt-5-mini-2025-08-07": {
    name: "gpt-5-mini-2025-08-07 on 302.AI",
    context: 400000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gpt-5-nano": {
    name: "gpt-5-nano on 302.AI",
    context: 400000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gpt-5-nano-2025-08-07": {
    name: "gpt-5-nano-2025-08-07 on 302.AI",
    context: 400000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gpt-5-pro": {
    name: "gpt-5-pro on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gpt-5-pro-2025-10-06": {
    name: "gpt-5-pro-2025-10-06 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gpt-5.1": {
    name: "gpt-5.1 on 302.AI",
    context: 400000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gpt-5.1-2025-11-13": {
    name: "gpt-5.1-2025-11-13 on 302.AI",
    context: 400000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gpt-5.1-chat-latest": {
    name: "gpt-5.1-chat-latest on 302.AI",
    context: 128000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gpt-5.1-codex": {
    name: "gpt-5.1-codex on 302.AI",
    context: 400000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gpt-5.1-codex-mini": {
    name: "gpt-5.1-codex-mini on 302.AI",
    context: 200000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gpt-5.1-plus": {
    name: "gpt-5.1-plus on 302.AI",
    context: 400000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gpt-5.1-thinking-plus": {
    name: "gpt-5.1-thinking-plus on 302.AI",
    context: 400000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    reasoning: true,
  },
  "gpt-5.2": {
    name: "gpt-5.2 on 302.AI",
    context: 400000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gpt-5.2-2025-12-11": {
    name: "gpt-5.2-2025-12-11 on 302.AI",
    context: 400000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gpt-5.2-chat-latest": {
    name: "gpt-5.2-chat-latest on 302.AI",
    context: 128000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gpt-5.2-codex": {
    name: "gpt-5.2-codex on 302.AI",
    context: 200000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gpt-5.2-pro": {
    name: "gpt-5.2-pro on 302.AI",
    context: 128000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gpt-5.3-chat-latest": {
    name: "gpt-5.3-chat-latest on 302.AI",
    context: 128000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gpt-5.3-codex": {
    name: "gpt-5.3-codex on 302.AI",
    context: 200000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gpt-5.4": {
    name: "gpt-5.4 on 302.AI",
    context: 1050000,
    output: 32768,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gpt-5.4-mini": {
    name: "gpt-5.4-mini on 302.AI",
    context: 400000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gpt-5.4-mini-2026-03-17": {
    name: "gpt-5.4-mini-2026-03-17 on 302.AI",
    context: 400000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gpt-5.4-nano": {
    name: "gpt-5.4-nano on 302.AI",
    context: 400000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gpt-5.4-nano-2026-03-17": {
    name: "gpt-5.4-nano-2026-03-17 on 302.AI",
    context: 400000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gpt-5.4-pro": {
    name: "gpt-5.4-pro on 302.AI",
    context: 1050000,
    output: 32768,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "gpt-5.5": {
    name: "gpt-5.5 on 302.AI",
    context: 1050000,
    output: 32768,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "grok-2-vision-1212": {
    name: "grok-2-vision-1212 on 302.AI",
    context: 32768,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "grok-3": {
    name: "grok-3 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "grok-3-mini": {
    name: "grok-3-mini on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    reasoning: true,
  },
  "grok-4-0709": {
    name: "grok-4-0709 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "grok-4-1-fast-non-reasoning": {
    name: "grok-4-1-fast-non-reasoning on 302.AI",
    context: 256000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "grok-4-1-fast-reasoning": {
    name: "grok-4-1-fast-reasoning on 302.AI",
    context: 2000000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    reasoning: true,
  },
  "grok-4-fast-non-reasoning": {
    name: "grok-4-fast-non-reasoning on 302.AI",
    context: 256000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "grok-4-fast-reasoning": {
    name: "grok-4-fast-reasoning on 302.AI",
    context: 2000000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    reasoning: true,
  },
  "grok-4.20-beta-0309-non-reasoning": {
    name: "grok-4.20-beta-0309-non-reasoning on 302.AI",
    context: 2000000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "grok-4.20-beta-0309-reasoning": {
    name: "grok-4.20-beta-0309-reasoning on 302.AI",
    context: 2000000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    reasoning: true,
  },
  "grok-4.20-multi-agent-beta-0309": {
    name: "grok-4.20-multi-agent-beta-0309 on 302.AI",
    context: 2000000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "grok-4.3": {
    name: "grok-4.3 on 302.AI",
    context: 1000000,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "grok-code-fast-1": {
    name: "grok-code-fast-1 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "hunyuan-code": {
    name: "hunyuan-code on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "hunyuan-functioncall": {
    name: "hunyuan-functioncall on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "hunyuan-lite": {
    name: "hunyuan-lite on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "hunyuan-pro": {
    name: "hunyuan-pro on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "hunyuan-role": {
    name: "hunyuan-role on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "hunyuan-standard": {
    name: "hunyuan-standard on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "hunyuan-standard-256K": {
    name: "hunyuan-standard-256K on 302.AI",
    context: 256000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "hunyuan-t1-20250321": {
    name: "hunyuan-t1-20250321 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    reasoning: true,
  },
  "hunyuan-t1-20250711": {
    name: "hunyuan-t1-20250711 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    reasoning: true,
  },
  "hunyuan-t1-latest": {
    name: "hunyuan-t1-latest on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    reasoning: true,
  },
  "hunyuan-turbos-20250226": {
    name: "hunyuan-turbos-20250226 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "hunyuan-turbos-20250716": {
    name: "hunyuan-turbos-20250716 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "hunyuan-vision": {
    name: "hunyuan-vision on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "kat-coder": {
    name: "kat-coder on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "kimi-for-coding": {
    name: "kimi-for-coding on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "kimi-k2-0711-preview": {
    name: "kimi-k2-0711-preview on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "kimi-k2-0905-preview": {
    name: "kimi-k2-0905-preview on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "kimi-k2-250711": {
    name: "kimi-k2-250711 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "kimi-k2-thinking": {
    name: "kimi-k2-thinking on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    reasoning: true,
  },
  "kimi-k2-thinking-turbo": {
    name: "kimi-k2-thinking-turbo on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    reasoning: true,
  },
  "kimi-k2-turbo-preview": {
    name: "kimi-k2-turbo-preview on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    reasoning: true,
  },
  "kimi-k2.5": {
    name: "kimi-k2.5 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "kimi-k2.6": {
    name: "kimi-k2.6 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "kimi-latest": {
    name: "kimi-latest on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "llama-4-maverick": {
    name: "llama-4-maverick on 302.AI",
    context: 1048576,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    openWeights: true,
  },
  "llama-4-scout": {
    name: "llama-4-scout on 302.AI",
    context: 1048576,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    openWeights: true,
  },
  "llama3.1-405b": {
    name: "llama3.1-405b on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    openWeights: true,
  },
  "llama3.1-70b": {
    name: "llama3.1-70b on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    openWeights: true,
  },
  "llama3.1-8b": {
    name: "llama3.1-8b on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    openWeights: true,
  },
  "llama3.2-11b": {
    name: "llama3.2-11b on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    openWeights: true,
  },
  "llama3.2-90b": {
    name: "llama3.2-90b on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    openWeights: true,
  },
  "llama3.3-70b": {
    name: "llama3.3-70b on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    openWeights: true,
  },
  "marco-o1": {
    name: "marco-o1 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    openWeights: true,
  },
  "ministral-14b-2512": {
    name: "ministral-14b-2512 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    openWeights: true,
  },
  "ministral-3b-2512": {
    name: "ministral-3b-2512 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    openWeights: true,
  },
  "ministral-8b-2512": {
    name: "ministral-8b-2512 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    openWeights: true,
  },
  "mistral-large-2": {
    name: "mistral-large-2 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "mistral-large-2411": {
    name: "mistral-large-2411 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "mistral-large-2512": {
    name: "mistral-large-2512 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "mistral-large-latest": {
    name: "mistral-large-latest on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "mistral-medium-latest": {
    name: "mistral-medium-latest on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "mistral-small-2503": {
    name: "mistral-small-2503 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    openWeights: true,
  },
  "mistral-small-latest": {
    name: "mistral-small-latest on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    openWeights: true,
  },
  "moonshot-v1-8k": {
    name: "moonshot-v1-8k on 302.AI",
    context: 8192,
    output: 4096,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "moonshot-v1-8k-vision-preview": {
    name: "moonshot-v1-8k-vision-preview on 302.AI",
    context: 8192,
    output: 4096,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "pixtral-large-2411": {
    name: "pixtral-large-2411 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "pixtral-large-latest": {
    name: "pixtral-large-latest on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "qwen-mt-flash": {
    name: "qwen-mt-flash on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "qwen-mt-lite": {
    name: "qwen-mt-lite on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "qwen-plus-2025-09-11": {
    name: "qwen-plus-2025-09-11 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "qwen-plus-2025-12-01": {
    name: "qwen-plus-2025-12-01 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "qwen-vl-max-2025-08-13": {
    name: "qwen-vl-max-2025-08-13 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "qwen-vl-max-latest": {
    name: "qwen-vl-max-latest on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "qwen-vl-plus-2025-08-15": {
    name: "qwen-vl-plus-2025-08-15 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "qwen-vl-plus-latest": {
    name: "qwen-vl-plus-latest on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "qwen3-coder-plus-2025-09-23": {
    name: "qwen3-coder-plus-2025-09-23 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "qwen3-max": {
    name: "qwen3-max on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "qwen3-max-2025-09-23": {
    name: "qwen3-max-2025-09-23 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "qwen3-max-2026-01-23": {
    name: "qwen3-max-2026-01-23 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "qwen3-max-preview": {
    name: "qwen3-max-preview on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "qwen3-next-80b-a3b-instruct": {
    name: "qwen3-next-80b-a3b-instruct on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    openWeights: true,
  },
  "qwen3-vl-235b-a22b-instruct": {
    name: "qwen3-vl-235b-a22b-instruct on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    openWeights: true,
  },
  "qwen3-vl-235b-a22b-thinking": {
    name: "qwen3-vl-235b-a22b-thinking on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    openWeights: true,
    reasoning: true,
  },
  "qwen3-vl-30b-a3b-instruct": {
    name: "qwen3-vl-30b-a3b-instruct on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    openWeights: true,
  },
  "qwen3-vl-30b-a3b-thinking": {
    name: "qwen3-vl-30b-a3b-thinking on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    openWeights: true,
    reasoning: true,
  },
  "qwen3-vl-32b-instruct": {
    name: "qwen3-vl-32b-instruct on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    openWeights: true,
  },
  "qwen3-vl-32b-thinking": {
    name: "qwen3-vl-32b-thinking on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    openWeights: true,
    reasoning: true,
  },
  "qwen3-vl-flash": {
    name: "qwen3-vl-flash on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    openWeights: true,
  },
  "qwen3-vl-flash-2025-10-15": {
    name: "qwen3-vl-flash-2025-10-15 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    openWeights: true,
  },
  "qwen3-vl-plus": {
    name: "qwen3-vl-plus on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "qwen3-vl-plus-2025-09-23": {
    name: "qwen3-vl-plus-2025-09-23 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "qwen3-vl-plus-2025-12-19": {
    name: "qwen3-vl-plus-2025-12-19 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "qwen3.5-122b-a10b": {
    name: "qwen3.5-122b-a10b on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    openWeights: true,
  },
  "qwen3.5-27b": {
    name: "qwen3.5-27b on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    openWeights: true,
  },
  "qwen3.5-35b-a3b": {
    name: "qwen3.5-35b-a3b on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    openWeights: true,
  },
  "qwen3.5-397b-a17b": {
    name: "qwen3.5-397b-a17b on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    openWeights: true,
  },
  "qwen3.5-flash": {
    name: "qwen3.5-flash on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    openWeights: true,
  },
  "qwen3.5-plus": {
    name: "qwen3.5-plus on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "qwen3.6-35b-a3b": {
    name: "qwen3.6-35b-a3b on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
    openWeights: true,
  },
  "qwen3.6-flash": {
    name: "qwen3.6-flash on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  "qwen3.6-plus": {
    name: "qwen3.6-plus on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text", "image"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  sonar: {
    name: "sonar on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "sonar-deep-research": {
    name: "sonar-deep-research on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "sonar-pro": {
    name: "sonar-pro on 302.AI",
    context: 200000,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "sonar-reasoning": {
    name: "sonar-reasoning on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    reasoning: true,
  },
  "sonar-reasoning-pro": {
    name: "sonar-reasoning-pro on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    reasoning: true,
  },
  "step-3.5-flash": {
    name: "step-3.5-flash on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    toolCall: true,
  },
  u1: {
    name: "u1 on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "u1-pro": {
    name: "u1-pro on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
  },
  "yi-lightning": {
    name: "yi-lightning on 302.AI",
    context: 131072,
    output: 16384,
    inputModalities: ["text"] as ModelModality[],
    outputModalities: ["text"] as ModelModality[],
    openWeights: true,
  },
};

// Pricing data: model ID → [input_price, output_price] (USD per 1M tokens)
const PRICING: Record<string, [number, number]> = {
  "Baichuan-M2": [0.319, 3.19],
  "Baichuan-M2-Plus": [1.6, 4.8],
  "Baichuan-M3": [1.573, 4.719],
  "Baichuan3-Turbo": [1.87, 1.87],
  "Baichuan3-Turbo-128k": [3.74, 3.74],
  Baichuan4: [15.73, 15.73],
  "DeepSeek-R1-0528": [0.6, 2.3],
  "Doubao-1.5-lite-32k": [0.055, 0.099],
  "Doubao-1.5-pro-256k": [0.88, 1.43],
  "Doubao-1.5-pro-32k": [0.132, 0.319],
  "Doubao-Seed-2.0-Code": [0.46, 2.29],
  "Doubao-Seed-2.0-lite": [0.128, 0.78],
  "Doubao-Seed-2.0-mini": [0.115, 0.115],
  "Doubao-Seed-2.0-pro": [0.46, 2.28],
  "KAT-Coder-Pro-V1": [0.57, 2.28],
  "LongCat-Flash-Chat": [0.2, 1],
  "M2-Her": [0.3, 1.2],
  "MAI-DS-R1": [0.66, 2.53],
  "MiniMax-M1": [0.132, 1.254],
  "MiniMax-M2": [0.33, 1.32],
  "MiniMax-M2.1": [0.3, 1.2],
  "MiniMax-M2.5": [0.3, 1.2],
  "MiniMax-M2.5-highspeed": [0.6, 4.8],
  "MiniMax-M2.7": [0.3, 1.2],
  "MiniMax-M2.7-highspeed": [0.6, 4.8],
  "MiniMax-Text-01": [0.154, 1.232],
  "Phi-4-mini-reasoning": [0.1, 0.5],
  "Phi-4-reasoning": [1, 2],
  "SenseChat-5": [6.6, 15.4],
  "SenseChat-Turbo": [0.33, 0.77],
  "SenseNova-V6-Pro": [0.55, 1.43],
  "SenseNova-V6-Reasoner": [0.66, 2.53],
  "SenseNova-V6-Turbo": [0.275, 0.715],
  "abab6.5s-chat": [0.154, 0.154],
  "abab7-chat-preview": [1.54, 1.54],
  "chat-latest": [5, 30],
  "claude-3-5-haiku": [0.8, 4],
  "claude-haiku-4-5-20251001": [1, 5],
  "claude-opus-4-1-20250805": [15, 75],
  "claude-opus-4-1-20250805-thinking": [15, 75],
  "claude-opus-4-20250514": [15, 75],
  "claude-opus-4-20250514-thinking": [15, 75],
  "claude-opus-4-5-20251101": [5, 25],
  "claude-opus-4-6": [5, 25],
  "claude-opus-4-6-thinking": [5, 25],
  "claude-opus-4-7": [5, 25],
  "claude-sonnet-4-20250514": [3, 15],
  "claude-sonnet-4-20250514-thinking": [3, 15],
  "claude-sonnet-4-5-20250929": [3, 15],
  "claude-sonnet-4-5-20250929-thinking": [3, 15],
  "claude-sonnet-4-6": [3, 15],
  "claude-sonnet-4-6-thinking": [3, 15],
  "deepseek-r1": [0.6, 2.3],
  "deepseek-r1-aliyun": [0.6, 2.3],
  "deepseek-r1-baidu": [0.6, 2.3],
  "deepseek-r1-huoshan": [0.6, 2.3],
  "deepseek-r1-huoshan-0528": [0.6, 2.3],
  "deepseek-v3-0324": [0.55, 1.32],
  "deepseek-v3-aliyun": [0.3, 1.2],
  "deepseek-v3-baidu": [0.3, 1.2],
  "deepseek-v3-huoshan": [0.3, 1.2],
  "deepseek-v3.1": [0.286, 1.15],
  "deepseek-v3.1-huoshan": [0.57, 1.71],
  "deepseek-v3.1-thinking": [0.286, 1.15],
  "deepseek-v3.2": [0.29, 0.43],
  "deepseek-v3.2-exp": [0.29, 0.43],
  "deepseek-v3.2-exp-thinking": [0.29, 0.43],
  "deepseek-v3.2-thinking": [0.29, 0.43],
  "deepseek-v4-flash": [0.143, 0.286],
  "deepseek-v4-pro": [1.72, 3.43],
  "deepseek-vl2": [0.165, 0.165],
  "devstral-2512": [1.1, 3.3],
  "devstral-medium-2507": [0.44, 2.2],
  "devstral-small-2505": [0.11, 0.33],
  "devstral-small-2507": [0.11, 0.33],
  "doubao-1-5-thinking-pro-250415": [0.6, 2.3],
  "doubao-1-5-thinking-pro-vision-250415": [0.6, 2.3],
  "doubao-1-5-thinking-vision-pro-250428": [0.55, 1.43],
  "doubao-1.5-ui-tars-250328": [0.5, 1.7],
  "doubao-1.5-vision-lite-250315": [0.21, 0.64],
  "doubao-1.5-vision-pro-250328": [0.43, 1.29],
  "doubao-seed-1-6-250615": [0.121, 0.33],
  "doubao-seed-1-6-flash-250615": [0.023, 0.231],
  "doubao-seed-1-6-thinking-250615": [0.121, 1.21],
  "doubao-seed-1-6-vision-250815": [0.12573, 0.12573],
  "doubao-seed-1-8-251215": [0.1143, 0.286],
  "doubao-seed-code-preview-251028": [0.1715, 1.1429],
  "doubao-seed-code-preview-latest": [0.0515, 0.343],
  "ernie-4.0-8k": [5.5, 14.3],
  "ernie-4.0-turbo-128k": [3, 8.6],
  "ernie-4.0-turbo-8k": [3.3, 9.46],
  "ernie-4.5-8k-preview": [0.66, 2.53],
  "ernie-4.5-turbo-128k": [0.132, 0.55],
  "ernie-4.5-turbo-vl-32k": [0.495, 1.43],
  "ernie-5.0-thinking-latest": [0.946, 1.573],
  "ernie-5.0-thinking-preview": [0.946, 1.573],
  "ernie-x1-turbo-32k": [0.165, 0.66],
  "ernie-x1.1-preview": [0.156, 0.627],
  "gemini-2.0-flash": [0.11, 0.44],
  "gemini-2.0-flash-exp-search": [0.2, 0.6],
  "gemini-2.0-flash-lite": [0.075, 0.3],
  "gemini-2.0-flash-search": [0.2, 0.6],
  "gemini-2.5-flash": [0.3, 2.5],
  "gemini-2.5-flash-deepsearch": [5, 25],
  "gemini-2.5-flash-lite": [0.1, 0.4],
  "gemini-2.5-flash-lite-preview-09-2025": [0.1, 0.4],
  "gemini-2.5-flash-nothink": [0.3, 2.5],
  "gemini-2.5-flash-preview-09-2025": [0.3, 2.5],
  "gemini-2.5-flash-search": [0.3, 2.5],
  "gemini-2.5-pro": [1.25, 10],
  "gemini-2.5-pro-deepsearch": [5, 35],
  "gemini-2.5-pro-search": [1.25, 10],
  "gemini-3-flash-preview": [0.5, 3],
  "gemini-3-pro-preview": [2, 12],
  "gemini-3.1-flash-lite-preview": [0.25, 1.5],
  "gemini-3.1-pro-preview": [2, 12],
  "gemma-2-27b": [0.18, 0.18],
  "glm-4-air-250414": [0.07, 0.07],
  "glm-4-flash-250414": [0.0014, 0.0014],
  "glm-4.1v-thinking-flashx": [0.3, 0.3],
  "glm-4.5": [0.286, 1.143],
  "glm-4.5-air": [0.1143, 0.286],
  "glm-4.5-airx": [0.572, 1.714],
  "glm-4.5-x": [1.143, 2.29],
  "glm-4.5v": [0.29, 0.86],
  "glm-4.6": [0.286, 1.142],
  "glm-4.6v": [0.145, 0.43],
  "glm-4.7": [0.286, 1.142],
  "glm-4.7-flashx": [0.0715, 0.429],
  "glm-5": [0.6, 2.6],
  "glm-5-turbo": [0.72, 3.2],
  "glm-5.1": [0.86, 3.5],
  "glm-5v-turbo": [0.72, 3.2],
  "glm-for-coding": [0.086, 0.343],
  "gpt-5": [1.25, 10],
  "gpt-5-2025-08-07": [1.25, 10],
  "gpt-5-chat-latest": [1.25, 10],
  "gpt-5-codex": [1.25, 10],
  "gpt-5-mini": [0.25, 2],
  "gpt-5-mini-2025-08-07": [0.25, 2],
  "gpt-5-nano": [0.05, 0.4],
  "gpt-5-nano-2025-08-07": [0.05, 0.4],
  "gpt-5-pro": [15, 120],
  "gpt-5-pro-2025-10-06": [15, 120],
  "gpt-5.1": [1.25, 10],
  "gpt-5.1-2025-11-13": [1.25, 10],
  "gpt-5.1-chat-latest": [1.25, 10],
  "gpt-5.1-codex": [1.25, 10],
  "gpt-5.1-codex-mini": [0.25, 2],
  "gpt-5.1-plus": [1.25, 10],
  "gpt-5.1-thinking-plus": [1.25, 10],
  "gpt-5.2": [1.75, 14],
  "gpt-5.2-2025-12-11": [1.75, 14],
  "gpt-5.2-chat-latest": [1.75, 14],
  "gpt-5.2-codex": [1.75, 14],
  "gpt-5.2-pro": [21, 168],
  "gpt-5.3-chat-latest": [1.75, 14],
  "gpt-5.3-codex": [1.75, 14],
  "gpt-5.4": [2.5, 15],
  "gpt-5.4-mini": [0.75, 4.5],
  "gpt-5.4-mini-2026-03-17": [0.75, 4.5],
  "gpt-5.4-nano": [0.2, 1.25],
  "gpt-5.4-nano-2026-03-17": [0.2, 1.25],
  "gpt-5.4-pro": [30, 180],
  "gpt-5.5": [5, 30],
  "grok-2-vision-1212": [2, 10],
  "grok-3": [3, 15],
  "grok-3-mini": [0.3, 0.5],
  "grok-4-0709": [3, 15],
  "grok-4-1-fast-non-reasoning": [0.2, 0.5],
  "grok-4-1-fast-reasoning": [0.2, 0.5],
  "grok-4-fast-non-reasoning": [0.2, 0.5],
  "grok-4-fast-reasoning": [0.2, 0.5],
  "grok-4.20-beta-0309-non-reasoning": [2, 6],
  "grok-4.20-beta-0309-reasoning": [2, 6],
  "grok-4.20-multi-agent-beta-0309": [2, 6],
  "grok-4.3": [1.25, 2.5],
  "grok-code-fast-1": [0.2, 1.5],
  "hunyuan-code": [0.627, 1.254],
  "hunyuan-functioncall": [0.627, 1.254],
  "hunyuan-lite": [0.11, 0.11],
  "hunyuan-pro": [4.73, 15.73],
  "hunyuan-role": [0.627, 1.254],
  "hunyuan-standard": [0.704, 0.792],
  "hunyuan-standard-256K": [2.42, 9.46],
  "hunyuan-t1-20250321": [0.165, 0.66],
  "hunyuan-t1-20250711": [0.165, 0.66],
  "hunyuan-t1-latest": [0.165, 0.66],
  "hunyuan-turbos-20250226": [0.132, 0.33],
  "hunyuan-turbos-20250716": [0.132, 0.33],
  "hunyuan-vision": [28.6, 28.6],
  "kat-coder": [0.3, 1.2],
  "kimi-for-coding": [0.343, 1.37],
  "kimi-k2-0711-preview": [0.633, 2.53],
  "kimi-k2-0905-preview": [0.62854, 2.5146],
  "kimi-k2-250711": [0.6325, 2.53],
  "kimi-k2-thinking": [0.575, 2.3],
  "kimi-k2-thinking-turbo": [1.15, 8.29],
  "kimi-k2-turbo-preview": [1.257, 9.119],
  "kimi-k2.5": [0.627, 3.3],
  "kimi-k2.6": [0.95, 4],
  "kimi-latest": [0.315, 1.573],
  "llama-4-maverick": [1, 1],
  "llama-4-scout": [0.5, 0.5],
  "llama3.1-405b": [5, 5],
  "llama3.1-70b": [1.5, 1.5],
  "llama3.1-8b": [0.5, 0.5],
  "llama3.2-11b": [0.5, 0.5],
  "llama3.2-90b": [2, 2],
  "llama3.3-70b": [0.9, 0.9],
  "marco-o1": [0.2, 0.2],
  "ministral-14b-2512": [0.33, 0.33],
  "ministral-3b-2512": [0.33, 0.33],
  "ministral-8b-2512": [0.33, 0.33],
  "mistral-large-2": [5, 10],
  "mistral-large-2411": [2.2, 6.6],
  "mistral-large-2512": [1.1, 3.3],
  "mistral-large-latest": [2.2, 6.6],
  "mistral-medium-latest": [0.44, 6.6],
  "mistral-small-2503": [0.55, 0.55],
  "mistral-small-latest": [0.55, 0.55],
  "moonshot-v1-8k": [2.09, 2.09],
  "moonshot-v1-8k-vision-preview": [2.09, 2.09],
  "pixtral-large-2411": [2.2, 6.6],
  "pixtral-large-latest": [2.2, 6.6],
  "qwen-mt-flash": [0.1, 0.28],
  "qwen-mt-lite": [0.086, 0.23],
  "qwen-plus-2025-09-11": [0.12, 1.2],
  "qwen-plus-2025-12-01": [0.12, 1.2],
  "qwen-vl-max-2025-08-13": [0.23, 0.58],
  "qwen-vl-max-latest": [0.23, 0.572],
  "qwen-vl-plus-2025-08-15": [0.12, 0.3],
  "qwen-vl-plus-latest": [0.12, 0.3],
  "qwen3-coder-plus-2025-09-23": [0.572, 2.29],
  "qwen3-max": [0.46, 1.83],
  "qwen3-max-2025-09-23": [0.86, 3.43],
  "qwen3-max-2026-01-23": [0.36, 1.43],
  "qwen3-max-preview": [0.86, 3.43],
  "qwen3-next-80b-a3b-instruct": [0.143, 0.5715],
  "qwen3-vl-235b-a22b-instruct": [0.286, 1.143],
  "qwen3-vl-235b-a22b-thinking": [0.286, 2.86],
  "qwen3-vl-30b-a3b-instruct": [0.11, 0.43],
  "qwen3-vl-30b-a3b-thinking": [0.11, 1.1],
  "qwen3-vl-32b-instruct": [0.29, 1.143],
  "qwen3-vl-32b-thinking": [0.29, 2.86],
  "qwen3-vl-flash": [0.022, 0.22],
  "qwen3-vl-flash-2025-10-15": [0.022, 0.22],
  "qwen3-vl-plus": [0.143, 1.43],
  "qwen3-vl-plus-2025-09-23": [0.143, 1.43],
  "qwen3-vl-plus-2025-12-19": [0.143, 1.43],
  "qwen3.5-122b-a10b": [0.12, 0.92],
  "qwen3.5-27b": [0.09, 0.69],
  "qwen3.5-35b-a3b": [0.06, 0.46],
  "qwen3.5-397b-a17b": [0.171, 1.03],
  "qwen3.5-flash": [0.03, 0.29],
  "qwen3.5-plus": [0.12, 0.69],
  "qwen3.6-35b-a3b": [0.28, 1.7],
  "qwen3.6-flash": [0.19, 1.13],
  "qwen3.6-plus": [0.3, 1.8],
  sonar: [1.1, 1.1],
  "sonar-deep-research": [2.2, 8.8],
  "sonar-pro": [3.3, 16.5],
  "sonar-reasoning": [1.1, 5.5],
  "sonar-reasoning-pro": [2.2, 8.8],
  "step-3.5-flash": [0.11, 0.33],
  u1: [0.6, 0.6],
  "u1-pro": [1.2, 1.2],
  "yi-lightning": [0.15, 0.15],
};

function deriveFamily(id: string): string {
  const lower = id.toLowerCase();
  if (lower.includes("qwen3-vl") || lower.includes("qwen-vl")) return "qwen-vl";
  if (lower.includes("qwen3-coder") || lower.includes("qwen-coder")) return "qwen-coder";
  if (lower.includes("qwen3-max")) return "qwen3-max";
  if (lower.includes("qwen3-next")) return "qwen3-next";
  if (lower.includes("qwen3.6")) return "qwen3.6";
  if (lower.includes("qwen3.5")) return "qwen3.5";
  if (lower.includes("qwen3")) return "qwen3";
  if (lower.includes("qwen-mt")) return "qwen-mt";
  if (lower.includes("qwen")) return "qwen";
  if (
    lower.includes("glm-5v") ||
    lower.includes("glm-4.6v") ||
    lower.includes("glm-4.5v") ||
    lower.includes("glm-4.1v")
  )
    return "glm-v";
  if (lower.includes("glm-for-coding")) return "glm-coder";
  if (lower.includes("glm")) return "glm";
  if (lower.includes("kimi") || lower.includes("moonshot")) return "kimi";
  if (lower.includes("deepseek-v4")) return "deepseek-v4";
  if (lower.includes("deepseek-v3.2")) return "deepseek-v3.2";
  if (lower.includes("deepseek-v3.1")) return "deepseek-v3.1";
  if (lower.includes("deepseek-v3")) return "deepseek-v3";
  if (lower.includes("deepseek-r1")) return "deepseek-r1";
  if (lower.includes("deepseek-vl")) return "deepseek-vl";
  if (lower.includes("deepseek")) return "deepseek";
  if (lower.includes("claude-opus-4-7")) return "claude-opus-4-7";
  if (lower.includes("claude-opus-4-6")) return "claude-opus-4-6";
  if (lower.includes("claude-opus-4-5")) return "claude-opus-4-5";
  if (lower.includes("claude-opus-4-1")) return "claude-opus-4-1";
  if (lower.includes("claude-opus-4")) return "claude-opus-4";
  if (lower.includes("claude-sonnet-4-6")) return "claude-sonnet-4-6";
  if (lower.includes("claude-sonnet-4-5")) return "claude-sonnet-4-5";
  if (lower.includes("claude-sonnet-4")) return "claude-sonnet-4";
  if (lower.includes("claude-haiku")) return "claude-haiku";
  if (lower.includes("claude")) return "claude";
  if (lower.includes("gpt-5.5")) return "gpt-5.5";
  if (lower.includes("gpt-5.4")) return "gpt-5.4";
  if (lower.includes("gpt-5.3")) return "gpt-5.3";
  if (lower.includes("gpt-5.2")) return "gpt-5.2";
  if (lower.includes("gpt-5.1")) return "gpt-5.1";
  if (lower.includes("gpt-5")) return "gpt-5";
  if (lower.includes("chat-latest")) return "chatgpt";
  if (lower.includes("gemini-3.1")) return "gemini-3.1";
  if (lower.includes("gemini-3")) return "gemini-3";
  if (lower.includes("gemini-2.5")) return "gemini-2.5";
  if (lower.includes("gemini-2.0")) return "gemini-2.0";
  if (lower.includes("gemini")) return "gemini";
  if (lower.includes("gemma")) return "gemma";
  if (lower.includes("grok-4.3")) return "grok-4.3";
  if (lower.includes("grok-4.20") || lower.includes("grok-4-20")) return "grok-4.20";
  if (lower.includes("grok-4-1-fast") || lower.includes("grok-4.1-fast")) return "grok-4.1-fast";
  if (lower.includes("grok-4-fast") || lower.includes("grok-4-fast")) return "grok-4-fast";
  if (lower.includes("grok-4")) return "grok-4";
  if (lower.includes("grok-3")) return "grok-3";
  if (lower.includes("grok-2")) return "grok-2";
  if (lower.includes("grok-code")) return "grok-code";
  if (lower.includes("grok")) return "grok";
  if (lower.includes("doubao-seed-2") || lower.includes("doubao-seed-2")) return "doubao-seed-2";
  if (lower.includes("doubao-seed-1") || lower.includes("doubao-seed-1")) return "doubao-seed-1";
  if (lower.includes("doubao-1.5") || lower.includes("doubao-1-5")) return "doubao-1.5";
  if (lower.includes("doubao")) return "doubao";
  if (lower.includes("minimax-m2.7")) return "minimax-m2.7";
  if (lower.includes("minimax-m2.5")) return "minimax-m2.5";
  if (lower.includes("minimax-m2.1")) return "minimax-m2.1";
  if (lower.includes("minimax-m2") || lower.includes("m2-her")) return "minimax-m2";
  if (lower.includes("minimax-m1")) return "minimax-m1";
  if (lower.includes("minimax-text")) return "minimax-text";
  if (lower.includes("abab")) return "abab";
  if (lower.includes("minimax")) return "minimax";
  if (lower.includes("ernie-5")) return "ernie-5";
  if (lower.includes("ernie-4.5")) return "ernie-4.5";
  if (lower.includes("ernie-4")) return "ernie-4";
  if (lower.includes("ernie-x1")) return "ernie-x1";
  if (lower.includes("ernie")) return "ernie";
  if (lower.includes("hunyuan-t1")) return "hunyuan-t1";
  if (lower.includes("hunyuan-turbos")) return "hunyuan-turbos";
  if (lower.includes("hunyuan")) return "hunyuan";
  if (lower.includes("baichuan-m3")) return "baichuan-m3";
  if (lower.includes("baichuan-m2")) return "baichuan-m2";
  if (lower.includes("baichuan3") || lower.includes("baichuan4")) return "baichuan";
  if (lower.includes("llama-4")) return "llama-4";
  if (lower.includes("llama3.3")) return "llama-3.3";
  if (lower.includes("llama3.2")) return "llama-3.2";
  if (lower.includes("llama3.1")) return "llama-3.1";
  if (lower.includes("llama")) return "llama";
  if (lower.includes("marco")) return "marco";
  if (lower.includes("mistral-large")) return "mistral-large";
  if (lower.includes("mistral-medium")) return "mistral-medium";
  if (lower.includes("mistral-small")) return "mistral-small";
  if (lower.includes("devstral-medium")) return "devstral-medium";
  if (lower.includes("devstral-small")) return "devstral-small";
  if (lower.includes("devstral")) return "devstral";
  if (lower.includes("ministral")) return "ministral";
  if (lower.includes("pixtral")) return "pixtral";
  if (lower.includes("mistral")) return "mistral";
  if (lower.includes("sonar")) return "sonar";
  if (lower.includes("phi-4")) return "phi";
  if (lower.includes("mai-ds")) return "mai-ds";
  if (lower.includes("yi")) return "yi";
  if (lower.includes("u1")) return "u1";
  if (lower.includes("kat-coder") || lower.includes("kat-coder")) return "kat-coder";
  if (lower.includes("longcat")) return "longcat";
  if (lower.includes("step")) return "step";
  if (lower.includes("sensenova") || lower.includes("sensechat")) return "sensenova";
  if (lower.includes("autoglm")) return "autoglm";
  return "other";
}

export async function scrape(): Promise<ScrapeResult> {
  const today = new Date().toISOString().split("T")[0] as string;
  const models: Model[] = [];

  for (const [id, info] of Object.entries(MODELS)) {
    const prices = PRICING[id];
    if (!prices) {
      console.warn(`[302ai] Skipping ${id}: no pricing data`);
      continue;
    }

    const pricing: Pricing = {
      input: prices[0],
      output: prices[1],
    };

    const model: Model = {
      id,
      name: info.name,
      family: deriveFamily(id),
      limit: { context: info.context, output: info.output },
      modalities: {
        input: info.inputModalities,
        output: info.outputModalities,
      },
      pricing,
      release_date: today,
      last_updated: today,
    };

    if (info.toolCall) model.tool_call = true;
    if (info.openWeights) model.open_weights = true;
    if (info.reasoning) model.reasoning = true;

    models.push(defineModel(model));
  }

  return { provider, models };
}
